### ISSUE TITLE
Define a remote interface for the STS

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspace-dcp/decentralized-claims-protocol#13]
We need to define an interface for the STS based on the OAuth2 client credential flow for remote access. This should include a way to specify access token scopes.

**Comment by jimmarino** [comment]
This is already defined in the Base Identity Protocol document, [Section 6](https://github.com/eclipse-tractusx/identity-trust/issues/13).

I think we should close this out as completed and not write any additional text as details should be taken directly from the OAuth specification referenced in that section.

**Comment by paullatzelsperger** [comment]
As far as I can see, the [OAuth2 standard](https://www.rfc-editor.org/rfc/rfc6749.html#section-4.4.2) only specifies the use of a `scope` and a `grant_type`. But since we are using a parameter named `bearer_access_scope`, we should mention that. 
In addition, we will need to be able to specify additional claims cf. [base protocol](https://github.com/eclipse-tractusx/identity-trust/blob/main/specifications/M1/identity.protocol.base.md#41-self-issued-id-token-contents).

**Comment by paullatzelsperger** [comment]
Actually, [Section 8.2](https://datatracker.ietf.org/doc/html/rfc6749#section-8.2) specifies how additional parameters, such as the `bearer_access_scope` are handled. With that, the REST API is fully specified by the OAuth2 standard, no need to redefine.
