### ISSUE TITLE
Add correlation ids to `CredentialRequestMessage` and `CredentialMessage`

### ISSUE THREAD

**Issue by jimmarino** [eclipse-dataspace-dcp/decentralized-claims-protocol#70]
### What's missing?

There are no correlation ids for issuance message exchanges. These are needed for associating async message requests and replies for issuance and idempotent behavior.

### Why should it be in the spec?

See above.

### Where should this be added?

The presentation flow and issuance flow.

**Comment by nikschul** [comment]
Hi @jimmarino,
I have a couple of questions regarding this issue, since I am quite new to the DCP.

- I guess for this I only have to change the specification files `credential.issuance.protocol.md` and `verifiable.presentation.protocol.md` where `CredentialRequestMessage` and `CredentialMessage` is found, correct?
- Shall I add the correlation ID as an additional property to the  `CredentialRequestMessage` and `CredentialMessage` JSON objects? But then I am not exactly should when a correlation ID should be created and when should it be send with another request.

Kind regards
Niklas

**Comment by jimmarino** [comment]
Hi @nikschul 

Looking at this, I think the flow can be simplified. Only a provider request id must be passed as part of the response to a credential request from the client. So:

- The `CredentialRequestMessage` response (201) contains a body that should be of type `CredentialStatus` (this corresponds to the credential status endpoint), which already contains a `requestId` property.
- The Storage API CredentialMessage must be updated to include the `requestId` property 

Does that make sense? @wolf4ood what do you think?

**Comment by wolf4ood** [comment]
Yes i guess we can just return the `CredentialStatus` in the response of a `CredentialRequestMessage` so the client can track the async `CredentialMessage` with the same `requestId`
